
#环境配置
server:
  port: 80
  servlet:
    #应用访问路径
    context-path: /
  tomcat:
    threads:
      #tomcat最大线程数，默认200
      max: 800
      #tomcat启动初始化线程数，默认25
      min-spare: 30
    uri-encoding: UTF-8
#log配置
logging:
  level:
    com.jzweb: debug
    org.springframework: warn

spring:
  application:
    name: hello
  #模板引擎
  thymeleaf:
    mode: html
    encoding: UTF-8
    cache: false
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB